//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBloodDonation.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodBankStockTable
    {
        public int BloodBankStockID { get; set; }
        public Nullable<int> BloodBankID { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Description { get; set; }
    
        public virtual BloodBankTable BloodBankTable { get; set; }
        public virtual BloodGroupsTable BloodGroupsTable { get; set; }
    }
}
