//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBloodDonation.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorTable
    {
        public int DonarID { get; set; }
        public string FullName { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> LastDonationDate { get; set; }
        public string CNIC { get; set; }
        public string Location { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual BloodGroupsTable BloodGroupsTable { get; set; }
        public virtual CityTable CityTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
